# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Yajatime' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  
  node_modules_path = '../node_modules'

  pod 'React', path: "#{node_modules_path}/react-native"

  pod 'yoga', path: "#{node_modules_path}/react-native/ReactCommon/yoga/yoga.podspec"
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  # Pods for Yajatime
  pod 'Firebase'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios/RNFirebase.podspec'
  pod 'FirebaseAuth', :modular_headers => true
  pod 'FirebaseFirestore'
  pod 'FirebaseFunctions'

  pod 'FBSDKCoreKit', :modular_headers => true
  pod 'FBSDKLoginKit', :modular_headers => true

  target 'YajatimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
    end
end
